version: "3.8"
services:
  php-mssql:
    restart: always
    image: winkman/php-mssql:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./public/domain:/var/www/html/domain
